"""ONNX Runtime inference path — an optimized alternative to the Keras classifier.

Same public interface as `classifier.WasteClassifier` (load/predict/is_ready),
so it's a drop-in swap. Benchmarked at ~12.75x lower latency and ~67% smaller
on disk than the Keras model (see artifacts/metrics/onnx_benchmark.json,
generated by `python -m waste_classifier.ml.export_onnx`). Not wired in as the
default path — Grad-CAM needs a real Keras model with gradient tape support,
which ONNX Runtime (inference-only) can't provide — but this is a genuine,
usable optimized-serving option for a deployment that doesn't need Grad-CAM.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from PIL import Image

from waste_classifier import config
from waste_classifier.ml.classifier import Prediction

DEFAULT_ONNX_PATH = config.MODEL_PATH.with_suffix(".onnx")


class OnnxWasteClassifier:
    """Loads the ONNX-exported model once and serves predictions via onnxruntime."""

    def __init__(
        self,
        onnx_path: Path = DEFAULT_ONNX_PATH,
        class_names_path: Path = config.CLASS_NAMES_PATH,
    ) -> None:
        self._session = None
        self._input_name: str | None = None
        self._class_names: list[str] = []
        self._onnx_path = onnx_path
        self._class_names_path = class_names_path

    @property
    def is_ready(self) -> bool:
        return self._session is not None

    def load(self) -> None:
        import onnxruntime as ort

        if not self._onnx_path.exists():
            return

        self._session = ort.InferenceSession(
            str(self._onnx_path), providers=["CPUExecutionProvider"]
        )
        self._input_name = self._session.get_inputs()[0].name
        with open(self._class_names_path) as f:
            self._class_names = json.load(f)

    def predict(self, image: Image.Image) -> Prediction:
        if not self.is_ready:
            raise RuntimeError("ONNX model is not loaded. Call load() first.")

        img = image.convert("RGB").resize(config.IMG_SIZE)
        arr = np.expand_dims(np.array(img, dtype=np.float32), axis=0)

        outputs = self._session.run(None, {self._input_name: arr})
        preds = outputs[0][0]
        idx = int(np.argmax(preds))
        label = self._class_names[idx]

        probabilities = {
            name: round(float(score) * 100, 2) for name, score in zip(self._class_names, preds)
        }

        return Prediction(
            label=label,
            label_index=idx,
            confidence=round(float(preds[idx]) * 100, 2),
            recyclable=label in config.RECYCLABLE_CLASSES,
            probabilities=probabilities,
        )
